# *****************************************************************************
# * Copyright 2020 Amazon.com, Inc. and its affiliates. All Rights Reserved.  *
#                                                                             *
# Licensed under the Amazon Software License (the "License").                 *
#  You may not use this file except in compliance with the License.           *
# A copy of the License is located at                                         *
#                                                                             *
#  http://aws.amazon.com/asl/                                                 *
#                                                                             *
#  or in the "license" file accompanying this file. This file is distributed  *
#  on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either  *
#  express or implied. See the License for the specific language governing    *
#  permissions and limitations under the License.                             *
# *****************************************************************************

AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: "This CloudFormation stack will provision foundational resources required for you to run the Amazon AppFlow Immersion Day"
Resources:
  ####### S3 #########
  rAppFlowImmersionDayKmsCmk:
      Type: AWS::KMS::Key
      Properties:
        Description: AppFlow KMS key
        Enabled: true
        EnableKeyRotation: false
        KeyPolicy:
          Version: "2012-10-17"
          Id: "default"
          Statement:
            - Sid: "Enable IAM User Permissions"
              Effect: "Allow"
              Principal:
                AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
              Action: "kms:*"
              Resource: "*"


  rAppFlowImmersionDayKmsCmkAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: "alias/appflowcmk"        
      TargetKeyId: !Ref rAppFlowImmersionDayKmsCmk

  rAppFlowImmersionDayBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Join ['.',[ "appflow", !Ref 'AWS::Region', !Ref 'AWS::AccountId']]
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !GetAtt 'rAppFlowImmersionDayKmsCmk.Arn'

  rAppFlowImmersionDayBucketBucketPolicy:
    DependsOn:
      - rAppFlowImmersionDayBucket
      - rAppFlowImmersionDayKmsCmk
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref rAppFlowImmersionDayBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          # Forcing encryption at rest
          # Deny unencrypted object uploads.
          - Sid: DenyUnEncryptedObjectUploads
            Effect: Deny
            Principal: "*"
            Action: s3:PutObject
            Resource:
              - !Join ['', ['arn:aws:s3:::', !Ref rAppFlowImmersionDayBucket, /*]]
            Condition:
              StringNotLikeIfExists:
                s3:x-amz-server-side-encryption-aws-kms-key-id: !GetAtt 'rAppFlowImmersionDayKmsCmk.Arn'
          - Sid: DenyPublicListGrant
            Effect: Deny
            Principal:
              AWS: '*'
            Action: s3:PutBucketAcl
            Resource:
              - !Join ['', ['arn:aws:s3:::', !Ref rAppFlowImmersionDayBucket]]
            Condition:
              StringLike:
                s3:x-amz-grant-read:
                  - '*http://acs.amazonaws.com/groups/global/AllUsers*'
                  - '*http://acs.amazonaws.com/groups/global/AuthenticatedUsers*'
          # Forcing encryption in transit
          - Sid: SSLAccessOnly
            Action: s3:*
            Effect: Deny
            Resource:
              - !Join ['', ['arn:aws:s3:::', !Ref rAppFlowImmersionDayBucket, /*]]
            Condition:
              Bool:
                aws:SecureTransport: 'false'
            Principal: "*"
  
  rAppFlowGlueDataCatalogRole:
    Type: "AWS::IAM::Role"
    Properties: 
      RoleName: "MyAppFlowGDCRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "appflow.amazonaws.com" 
            Action: 
              - "sts:AssumeRole"
      Policies:
        - PolicyName: AllowAppFlowAccessToGDC
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: GlueDataCatalog
                Effect: Allow
                Action:
                  - glue:BatchCreatePartition
                  - glue:CreatePartitionIndex
                  - glue:DeleteDatabase
                  - glue:GetTableVersions
                  - glue:GetPartitions
                  - glue:BatchDeletePartition
                  - glue:DeleteTableVersion
                  - glue:UpdateTable
                  - glue:DeleteTable
                  - glue:DeletePartitionIndex
                  - glue:GetTableVersion
                  - glue:CreatePartition
                  - glue:UntagResource
                  - glue:UpdatePartition
                  - glue:TagResource
                  - glue:UpdateDatabase
                  - glue:CreateTable
                  - glue:BatchUpdatePartition
                  - glue:GetTables
                  - glue:BatchGetPartition
                  - glue:GetDatabases
                  - glue:GetPartitionIndexes
                  - glue:GetTable
                  - glue:GetDatabase
                  - glue:GetPartition
                  - glue:CreateDatabase
                  - glue:BatchDeleteTableVersion
                  - glue:BatchDeleteTable
                  - glue:DeletePartition
                Resource: "*"

  rAppFlowImmersionDayGlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Description: !Sub "Database to hold AppFlow ingested data"
        Name: "workshop_appflow_db"

Outputs:
  oAppFlowImmersionDayBucket:
    Value: !Ref rAppFlowImmersionDayBucket
    Description: "Amazon AppFlow Destination S3 Bucket"
  oAppFlowGlueDataCatalogRole:
    Value: !Ref rAppFlowGlueDataCatalogRole
    Description: "Amazon AppFlow IAM Role that allows AppFlow to create Glue Data Catalog resources"
  oAppFlowImmersionDayKMS:
    Value: !Ref rAppFlowImmersionDayKmsCmk
    Description: "KMS Key to be used by AppFlow for encryption of your data"